cc_binary(
    name = "packetdraw",
    srcs = [
        # headers
        "message.h",
        "graphics.h",

        # sources
        "graphics.c",
        "main.c",
    ],
    linkopts = ["-lSDL2"],
)
