cc_binary(
    name = "packetdraw",
    srcs = [
        # headers
        "message.h",
        "graphics.h",
        "server.h",
        "client.h",

        # sources
        "message.c",
        "graphics.c",
        "server.c",
        "client.c",
        "main.c",
    ],
    linkopts = ["-lSDL2", "-lpthread"],
)
