cc_library(
    name = "psy-uuid",
    srcs = [
        "clock.cc",
        "uuid.cc",
        "mac.cc",
    ],
    hdrs = [
        "clock.h",
        "common.h",
        "uuid.h",
        "mac.h",
    ],
    visibility = ["//visibility:public"]
)
