cc_library(
    name = "psycommon",
    srcs = [
        "codec.cc",
        "granulator.cc",
        "filesystem.cc",
        "xdg.cc",
    ],
    hdrs = [
        "codec.h",
        "granulator.h",
        "filesystem.h",
        "xdg.h",
    ],
    includes = [
        "./",
    ],
    visibility = ["//visibility:public"],
)
