cc_binary(
    name = "fmemopen-example",
    srcs = ["fmemopen.c"],
)

cc_binary(
    name = "signal-example",
    srcs = ["signal.c"],
)

cc_binary(
    name = "mmap-example",
    srcs = ["mmap.cc"],
)
