cc_binary(
    name = "fmemopen-example",
    srcs = ["fmemopen.c"],
)

cc_binary(
    name = "signal-example",
    srcs = ["signal.c"],
)

cc_binary(
    name = "mmap-example",
    srcs = ["mmap.cc"],
)

cc_binary(
    name = "shm-example",
    srcs = ["shm.c"],
    linkopts = [
        "-lrt",
        "-lpthread",
    ],
)

cc_binary(
    name = "dup-example",
    srcs = ["dup.c"]
)
